name: Main
on:
  pull_request:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: fetch lfs
      run: git lfs checkout

    - name: install nix
      uses: cachix/install-nix-action@v18

    - name: check flake
      run: nix flake check

    - name: build firmware
      run: nix build

    - name: get latest tag
      id: latest
      run: echo ::set-output name=version::$(git describe --abbrev=0 --tags --match 'v[0-9]*\.[0-9]*\.[0-9]*' | cut -c2-)

    - name: parse changelog
      id: changelog
      uses: coditory/changelog-parser@v1

    - name: create release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main' && steps.changelog.outputs.version != steps.latest.outputs.version
      with:
        files: result/little-buddy*.bin
        body: ${{ steps.changelog.outputs.description }}
        tag_name: ${{ steps.changelog.outputs.version }}
